#pragma checksum "LoginOrSignup.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "84CB2C2FAB8349BDA64411ADDC6573F5242B4AEE79366636287F6422F9005C0C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation;


namespace WPFPresentation {
    
    
    /// <summary>
    /// LoginOrSignup
    /// </summary>
    public partial class LoginOrSignup : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtLogin;
        
        #line default
        #line hidden
        
        
        #line 24 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblLoginEmail;
        
        #line default
        #line hidden
        
        
        #line 26 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtLoginEmail;
        
        #line default
        #line hidden
        
        
        #line 28 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblLoginPassword;
        
        #line default
        #line hidden
        
        
        #line 30 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox pwdLoginPassword;
        
        #line default
        #line hidden
        
        
        #line 32 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnLoginNotSignup;
        
        #line default
        #line hidden
        
        
        #line 45 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtSignup;
        
        #line default
        #line hidden
        
        
        #line 46 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSignupUsername;
        
        #line default
        #line hidden
        
        
        #line 48 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSignupUsername;
        
        #line default
        #line hidden
        
        
        #line 50 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSignupEmail;
        
        #line default
        #line hidden
        
        
        #line 52 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSignupEmail;
        
        #line default
        #line hidden
        
        
        #line 54 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSignupPassword;
        
        #line default
        #line hidden
        
        
        #line 56 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox pwdSignupPassword;
        
        #line default
        #line hidden
        
        
        #line 58 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSignupRetypePassword;
        
        #line default
        #line hidden
        
        
        #line 60 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox pwdSignupRetypePassword;
        
        #line default
        #line hidden
        
        
        #line 62 "LoginOrSignup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSignupNotLogin;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/loginorsignup.xaml", System.UriKind.Relative);
            
            #line 1 "LoginOrSignup.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.txtLogin = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.lblLoginEmail = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.txtLoginEmail = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.lblLoginPassword = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.pwdLoginPassword = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 6:
            this.btnLoginNotSignup = ((System.Windows.Controls.Button)(target));
            
            #line 32 "LoginOrSignup.xaml"
            this.btnLoginNotSignup.Click += new System.Windows.RoutedEventHandler(this.btnLoginNotSignup_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.txtSignup = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.lblSignupUsername = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.txtSignupUsername = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.lblSignupEmail = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.txtSignupEmail = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.lblSignupPassword = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.pwdSignupPassword = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 14:
            this.lblSignupRetypePassword = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.pwdSignupRetypePassword = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 16:
            this.btnSignupNotLogin = ((System.Windows.Controls.Button)(target));
            
            #line 62 "LoginOrSignup.xaml"
            this.btnSignupNotLogin.Click += new System.Windows.RoutedEventHandler(this.btnSignupNotLogin_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

